## -*- encoding: utf-8 -*-
## This file (vectorsScalarsAndMatrices.sagetex.sage) was *autogenerated* from vectorsScalarsAndMatrices.tex with sagetex.sty version 2022/08/21 v3.6.1.
import sagetex
_st_ = sagetex.SageTeXProcessor('vectorsScalarsAndMatrices', version='2022/08/21 v3.6.1', version_check=True)
_st_.endofdoc()
